---
- name: Install packages need into install apt repository
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Add the docker apt signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add the docker repository into sources list
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install docker and docker-compose
  package:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - docker-compose
    state: present

- name: Start service docker, if not started
  service:
    name: docker
    state: started
