---
- name: Converge
  hosts: all
  become: true

  vars:
    twitter_consumer_token: twitter_consumer_token
    twitter_consumer_token_secret: twitter_consumer_token_secret
    twitter_access_token: twitter_access_token
    twitter_access_token_secret: twitter_access_token_secret
    twitter_stream_track: twitter_stream_track

  roles:
    - role: ansible-role-twitter-docker
