---
dependency:
  name: galaxy
driver:
  name: openstack
lint: |
  set -e
  yamllint -c molecule/yaml-lint.yml .
  ansible-lint
  flake8
platforms:
  - name: twitter-docker-test
    image: Ubuntu 20.04 LTS x86_64
    flavor: m1.medium
provisioner:
  name: ansible
  log: true
  options:
    vvv: false
scenario:
  name: default
verifier:
  name: ansible
